name=ESP32 Controller
version=1.0.0
author=Tomoooji
maintainer=Tomoooji
sentence=Multiple classes for controlling ESP32 robot
paragraph=Provides Serial, PS4, I2C, and ESP-NOW controller classes for ESP32
category=Device Control
url=https://github.com/Tomoooji/esp32-controller
architectures=esp32
license=GPL-3.0
includes=ESP32_Controller_XXX.h
